### ISSUE TITLE
Style Deletion Button?

### ISSUE THREAD

**Issue by BlankFX1** [harukei-tech/sd-webui-extended-style-saver#1]
How can I delete Styles I don't need/want anymore? Did I miss a button?

**Comment by harukei-tech** [comment]
Sorry, delete button is not yet provided.
I hope to implement it in the near future, but do not consider it a high priority.

If you want to delete some saved style, please edit ``scripts/csv/ext_style.csv`` manually.

Pull requests to implement a delete button are also welcome 😃

**Comment by BlankFX1** [comment]
I pretty much appreciate your extension and don't want to miss it anymore. It just makes it so much easier to continue earlier work.
But as prompts are getting more complex with formatting, e.g. using Dynamic Prompts, it becomes tedious to clean the ext_style.csv by Hand.
Any chance to add this feature any time?
Maybe even comparable to the A1111 native Style Edit Dialog?

**Comment by harukei-tech** [comment]
@BlankFX1 
Thank you for using the sd-webui-extended-style-saver extension!

I have been busy of late and have not been able to add features.
However, I received your message that you are interested in this feature
 and have hastily implemented a delete button😃 

You can update sd-webui-extended-style-saver from the Extensions tab.
Please take advantage of it!
